services:
  nugb-gereb-form:
    build: .
    container_name: nugb-gereb-form
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      PORT: 3002
      CORS_ORIGIN: "https://guilhermegalvaosilva.github.io"
    volumes:
      - nugb-gereb-data:/app/data
    restart: unless-stopped

volumes:
  nugb-gereb-data:
